name: Dependabot

on:
  pull_request:

permissions:
  contents: read

jobs:
  dependabot:
    name: Auto Merge
    uses: Staffbase/gha-workflows/.github/workflows/template_automerge_dependabot.yml@7433384f8737623f2c8eb247427830629ce66d97 # v14.1.0
    with:
      force: true
    secrets:
      app_id: ${{ vars.STAFFBASE_ACTIONS_APP_ID }}
      private_key: ${{ secrets.STAFFBASE_ACTIONS_PRIVATE_KEY }}
